version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-python
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/root/SteamyReviews
    links:
      - dynamodb
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgres://test:test@postgres:5432/test
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMO_URL=http://dynamodb:8000
      - GAME_CACHE_PULL_ON_LOAD=1
      - UPDATE_GAME_ON_GET=0
  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile-dynamodb
    expose:
      - "8000"
    volumes:
      - /var/dynamodb
